### ISSUE TITLE
1 - Modulo de Disciplinas

### ISSUE THREAD

**Issue by GeloBom** [Arco-e-Machado/Gerador-de-testes-2024#1]
- [x] Requisito 1.1: Cadastrar Novas Disciplinas

Critérios:
⦁	O registro de disciplina é composto por nome
⦁	O campo nome é obrigatório
⦁	Não pode registrar uma disciplina com o mesmo nome
⦁	A disciplina deve armazenar informações sobre as matérias que serão relacionadas à ela posteriormente
Protótipo:

![Image](https://github.com/Arco-e-Machado/Gerador-de-testes-2024/assets/140113530/561b4b76-7c3f-47f7-bb3c-945b15c98042)

 

- [x] Requisito 1.2: Editar Disciplinas

	Critérios:
⦁	Os critérios de validação são os mesmos do Requisito 1.1

- [x] Requisito 1.3: Excluir Disciplinas

	Critérios:
⦁	Não deve ser possível excluir disciplinas com matérias e testes relacionados.

- [x] Requisito 1.4 Visualizar Todas as Disciplinas.

Critérios:
⦁	Deve exibir: Id e Nome

**Comment by LeoRodrigues133** [comment]
Finalizado o módulo de disciplinas, vou enviar para testes agora

**Comment by GeloBom** [comment]
Bug de Exclusão e Desserialização encontrado.

**Comment by GeloBom** [comment]
> Bug de Exclusão e Desserialização encontrado.

Resolvido.

**Comment by GeloBom** [comment]
Bug de edição encontrado:

- Gravar não atualiza o item da lista
